HOST: http://www.google.com/

--- Sample API v2 ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Users
API for getting users
--
List all users.
GET /users?limit={limit}&offset={offset}&sort={sort}&dir={dir}
< 200
< Content-Type: application/json
[
    {        
        "access": "rw",
        "agencyLimit": "0",
        "agencyStatus": "client-agency",
        "avgCpc": "11.018451",
        "avgPos": "3.91",
        "changeAccessRequest": "no-request",
        "clicks": "439",
        "convCost": "",
        "convCostValRate": "",
        "convRate": "",
        "convValue": "0",
        "conversions": "0",
        "credit": "0",
        "creditWithVat": "0",
        "ctr": "0.117915",
        "dayBudget": "0.0",
        "domain": "seznam.cz",
        "exhaustedBudget": "0",
        "id": "207100",
        "impressions": "372302",
        "ish": "100.0",
        "lowQuality": "0",
        "missImpressions": "0",
        "missedPrice": "0.0",
        "money": "4837.1",
        "notDisplayedMessages": "5",
        "relationName": "1200000aut@seznam.cz",
        "relationStatus": "agency",
        "rusUserId": "44355524",
        "selectAccess": "agency",
        "sendNotice": "0",
        "stoppedBySchedule": "0",
        "underForestThreshold": "0",
        "underLowerThreshold": "0",
        "username": "1200000aut",
        "verifiedInWallet": "0"
    },
    {        
        "access": "rw",
        "agencyLimit": "0",
        "agencyStatus": "client-agency",
        "avgCpc": "11.018451",
        "avgPos": "3.91",
        "changeAccessRequest": "no-request",
        "clicks": "439",
        "convCost": "",
        "convCostValRate": "",
        "convRate": "",
        "convValue": "0",
        "conversions": "0",
        "credit": "0",
        "creditWithVat": "0",
        "ctr": "0.117915",
        "dayBudget": "0.0",
        "domain": "seznam.cz",
        "exhaustedBudget": "0",
        "id": "207100",
        "impressions": "372302",
        "ish": "100.0",
        "lowQuality": "0",
        "missImpressions": "0",
        "missedPrice": "0.0",
        "money": "4837.1",
        "notDisplayedMessages": "5",
        "relationName": "huhu@seznam.cz",
        "relationStatus": "agency",
        "rusUserId": "44355524",
        "selectAccess": "agency",
        "sendNotice": "0",
        "stoppedBySchedule": "0",
        "underForestThreshold": "0",
        "underLowerThreshold": "0",
        "username": "1200000aut",
        "verifiedInWallet": "0"
    },
    {        
        "access": "rw",
        "agencyLimit": "0",
        "agencyStatus": "client-agency",
        "avgCpc": "11.018451",
        "avgPos": "3.91",
        "changeAccessRequest": "no-request",
        "clicks": "439",
        "convCost": "",
        "convCostValRate": "",
        "convRate": "",
        "convValue": "0",
        "conversions": "0",
        "credit": "0",
        "creditWithVat": "0",
        "ctr": "0.117915",
        "dayBudget": "0.0",
        "domain": "seznam.cz",
        "exhaustedBudget": "0",
        "id": "207100",
        "impressions": "372302",
        "ish": "100.0",
        "lowQuality": "0",
        "missImpressions": "0",
        "missedPrice": "0.0",
        "money": "4837.1",
        "notDisplayedMessages": "5",
        "relationName": "test@seznam.cz",
        "relationStatus": "agency",
        "rusUserId": "44355524",
        "selectAccess": "agency",
        "sendNotice": "0",
        "stoppedBySchedule": "0",
        "underForestThreshold": "0",
        "underLowerThreshold": "0",
        "username": "1200000aut",
        "verifiedInWallet": "0"
    },
    {        
        "access": "rw",
        "agencyLimit": "0",
        "agencyStatus": "client-agency",
        "avgCpc": "11.018451",
        "avgPos": "3.91",
        "changeAccessRequest": "no-request",
        "clicks": "439",
        "convCost": "",
        "convCostValRate": "",
        "convRate": "",
        "convValue": "0",
        "conversions": "0",
        "credit": "0",
        "creditWithVat": "0",
        "ctr": "0.117915",
        "dayBudget": "0.0",
        "domain": "seznam.cz",
        "exhaustedBudget": "0",
        "id": "207100",
        "impressions": "372302",
        "ish": "100.0",
        "lowQuality": "0",
        "missImpressions": "0",
        "missedPrice": "0.0",
        "money": "4837.1",
        "notDisplayedMessages": "5",
        "relationName": "huhu@seznam.cz",
        "relationStatus": "agency",
        "rusUserId": "44355524",
        "selectAccess": "agency",
        "sendNotice": "0",
        "stoppedBySchedule": "0",
        "underForestThreshold": "0",
        "underLowerThreshold": "0",
        "username": "Ondrej",
        "verifiedInWallet": "0"
    }
]

Ulozi jednoho uzivatele (ucet).
POST /users/{id}
< 200
< Content-Type: application/json
{
	"id": 1,
	"relationName": "franta"
}

Smaze propojeni uctu.
DELETE /users/{id}/disconnectAccount
< 200
< Content-Type: application/json
{	
	"id": 1,
	"relationName": "franta"
}